### ISSUE TITLE
Minor typo in script

### ISSUE THREAD

**Issue by realalexandergeorgiev** [phra/PEzor#15]
Line 386 and 387 of PEzor.sh is missing the "$" in front of BLOB.packed.
https://github.com/phra/PEzor/blob/master/PEzor.sh#L386
The final result is then put in the local directory as "BLOB.packed.$extension" (e.g. "./BLOB.packed.exe") instead of the target dir, because its treated as file not variable. 

Nothing major, but wanted to report it

**Comment by phra** [comment]
thanks for the report, the issue was fixed in https://github.com/phra/PEzor/commit/68ee4d808b717d452c125a841007c591a136b767.
