### ISSUE TITLE
Regex bug in CNA script

### ISSUE THREAD

**Issue by crimsoncore** [phra/PEzor#19]
Hi phra,

I'm running cobalt strike 4.2, kali (latest), and installed PEzor in the opt directory. when I run PEZor and pack an executable it works great. Execute-Assembly and tadaaaa... with the aggressor script, nothing happens:

[*] Tasked beacon to execute in-memory with args: '"coffee" "exit"'

Am I missing something here? Do I need to install it in a specific directory?

Cheers,
Luk

**Comment by phra** [comment]
PEzor has to be available via `$PATH` variable, is this your case?
anyway, you should be able to see the logs in the script console tab: can you check if you have any error?

**Comment by crimsoncore** [comment]
So, 

yes PEzor is in the path:

$PATH
bash: /home/kali/.local/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/kali/go/bin/:/opt/PEzor:/opt/PEzor/deps/donut_v0.9.3/:/opt/PEzor/deps/wclang/_prefix_PEzor_/bin/:


Output from the script console:

Copying  to /tmp/4643a6ff-3fb6-40e6-8346-31d403595888
[00:30:25] Uncaught exception: java.lang.StringIndexOutOfBoundsException: String index out of range: 0 at PEzor.cna:27

Kali version:
lsb_release -a
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2020.4
Codename:       kali-rolling

Hope this helps,
Luk

**Comment by phra** [comment]
> [00:30:25] Uncaught exception: java.lang.StringIndexOutOfBoundsException: String index out of range: 0 at PEzor.cna:27

[line 27](https://github.com/phra/PEzor/blob/master/aggressor/PEzor.cna#L27) is parsing the `-sdk` option. have you changed the cna script perhaps?

**Comment by crimsoncore** [comment]
nope, just a git clone and install - loading the original aggressor script from the cloned repo

**Comment by phra** [comment]
actually no idea. try to debug the script and let me know if you discover anything :smile:

**Comment by crimsoncore** [comment]
just checking the error:

String index out of range: 0 at PEzor.cna:206

it's at line 206 actually, not sure why I had 27 up there

![Xnip2020-11-18_01-33-48](https://user-images.githubusercontent.com/60291136/99467214-3a6f0e80-293e-11eb-9b72-03c65ab6be5c.jpg)

**Comment by crimsoncore** [comment]
> actually no idea. try to debug the script and let me know if you discover anything 😄

Are you running CS 4.2 ?

**Comment by phra** [comment]
can you paste your `execute-inmemory` command? i think the regex at [line 11](https://github.com/phra/PEzor/blob/master/aggressor/PEzor.cna#L11) is missing it.

**Comment by crimsoncore** [comment]
here you go:
execute-inmemory -format=dotnet /tmp/mimikatz.exe -z 2 -p '"coffee" "exit"'

(Mimikatz.exe in th /tmp/ directory

**Comment by crimsoncore** [comment]
in line 11 I removed the space between the ' and (, which throws this error...

[01:56:48] Uncaught exception: java.io.FileNotFoundException: /opt/cobaltstrike/execute (No such file or directory) at PEzor.cna:206

**Comment by phra** [comment]
try this regex instead ` ([\w\/\.][\w\/\.\-]*)`.

**Comment by crimsoncore** [comment]
Yep, that's it!!

works now, great - thanks for the help man. Was this a bug then?

Cheers,
Luk

**Comment by phra** [comment]
yes, anyway i am working on an updated cna script that i still have to commit to the repo. i will leave this issue open till then.

**Comment by crimsoncore** [comment]
Sure thing. pretty cool CNA!
