### ISSUE TITLE
sgn is a pain to install

### ISSUE THREAD

**Issue by nullcult** [phra/PEzor#2]
Even after following the install reference i can't get sgn to work on debian.

`sgn is missing from $PATH. `

What am i doing wrong.

**Comment by j1mrayn0r** [comment]
Did you add the go path to the PATH? such as: "export PATH=$PATH:/home/kali/go/bin"

**Comment by nullcult** [comment]
yes

**Comment by phra** [comment]
first of all, this software is released under a [warranty free license](https://github.com/phra/PEzor/blob/master/LICENSE) so try to be constructive in your bug reports.

> yes

probably not.

**Comment by b4cktr4ck2** [comment]
Had a similar issue, for some reason had to re-run "go get github.com/EgeBalci/sgn" after installation + restarting shell.
