### ISSUE TITLE
output null

### ISSUE THREAD

**Issue by sharp-shooter** [phra/PEzor#21]
when I run like this: PEzor.sh -unhook -antidebug -text -self -sleep=120 mimikatz/x64/mimikatz.exe -z 2  ,it works very well;
but when I run like this: PEzor.sh -unhook -antidebug -text -self -sleep=120 mimikatz/x64/mimikatz.exe -z 2 -p coffee exit, it output nothing,so I can't run with "-p",can you tell me why ? thank you !

**Comment by phra** [comment]
there are working examples in the README.
