### ISSUE TITLE
x86_64-w64-mingw32-clang++ is missing from $PATH. Check https://github.com/tpoechtrager/wclang to learn how to install it

### ISSUE THREAD

**Issue by KeparYTbcc** [phra/PEzor#30]
x86_64-w64-mingw32-clang++ is missing from $PATH. Check https://github.com/tpoechtrager/wclang to learn how to install it

**Comment by phra** [comment]
read the instructions printed during installation.

**Comment by 0xVIC** [comment]
> x86_64-w64-mingw32-clang++ is missing from $PATH. Check https://github.com/tpoechtrager/wclang to learn how to install it

in the end of the installation says:

export PATH=$PATH:~/go/bin/:/opt/PEzor:/opt/PEzor/deps/donut/:/opt/PEzor/deps/wclang/_prefix_PEzor_/bin/
