### ISSUE TITLE
PEzor payloads always leave cmd window open?

### ISSUE THREAD

**Issue by braimee** [phra/PEzor#41]
Hi,

I've generated PEzor payloads following some examples on the GitHub readme, and the good news is AV happily ignores them!  However, they always leave a blank command window open, and if it's closed the beacon dies.  Am I doing this wrong?

Here's what I used to generate the beacon I have running in the lab right now:

`Pezor -sgn -unhook -antidebug -text -syscalls -64 rawcode.bin`

**Comment by ceramic-skate0** [comment]
when you close it the shell goes with it. you might have to change startup info on the process create kinda stuff

**Comment by phra** [comment]
if you have any idea, feel free to send a PR to this repository!

**Comment by braimee** [comment]
Thanks for the responses everyone.  I wish I had the skills to suggest a PR :-).  But my original question is answered so I'll close this out.  Thanks again.
