### ISSUE TITLE
install.sh dependency is invalid

### ISSUE THREAD

**Issue by webca7** [phra/PEzor#66]
https://www.cobaltstrike.com/downloads/beacon.h   -->>   https://download.cobaltstrike.com/downloads/beacon.h

https://www.cobaltstrike.com/blog/cobalt-strike-infrastructure-changes/

**Comment by Chomikmarkus** [comment]
Any news about it:
![Screenshot_20211204-235411](https://user-images.githubusercontent.com/92059377/144725783-f88911c1-89aa-418c-b8fc-7f8702aef228.png)

**Comment by Chomikmarkus** [comment]
Solution download manually beacon.h, place it to PEzor root install directory, modify install.sh deleting string wget https://download.cobaltstrike.com/downloads/beacon.h
run bash install.sh and you are good to go! 
But this project is for now detected by most avs, triggered by donut! But waiting updates until that lovethepizzaaa;) cheerse

**Comment by phra** [comment]
thanks for the PR. i have already merged a PR containing this fix, please have a look at the updated `master` branch that should work on latest kali.
